### ISSUE TITLE
Test Lib Rejeitada

### ISSUE THREAD

**Issue by henrikemota** [mercadolibre/mobile-dependencies_whitelist#678]

**Comment by abruno-** [comment]
esta lib pesa mucho, podemos usar esta otra lib <link a otra opcion>

**Comment by abruno-** [comment]
:bulb: :ios:|:android: Bump Library Analysis - <lib_title> 
Package:Version: <package>:<version_old> -> <version_new>
Ticket: ticket_nro[link_to_ticket]
PR: [link]
If the library changes other dependencies, have we thoroughly evaluated them? yes|no
Lib size: xx KB
Conclusion: 
[..]
Additional Considerations:
Result: :white_check_mark: Approved | :x: Not Approved
